# Generated by Django 5.2.17 on 2026-08-23 14:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('experiments', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperimentMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('event_name', models.CharField(help_text='Matches the event_name in conversion_events', max_length=255)),
                ('metric_type', models.CharField(choices=[('PRIMARY', 'Primary'), ('SECONDARY', 'Secondary'), ('GUARDRAIL', 'Guardrail')], default='PRIMARY', max_length=20)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='experiments.experiment')),
            ],
            options={
                'db_table': 'experiment_metrics',
                'unique_together': {('experiment', 'name')},
            },
        ),
    ]
