# Generated by Django 5.2.17 on 2026-09-25 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='experimentmetric',
            name='aggregation',
            field=models.CharField(choices=[('CONVERSION', 'Share of users with the event'), ('MEAN_VALUE', 'Mean event value per exposed user')], default='CONVERSION', help_text='CONVERSION: users with the event / exposed users. MEAN_VALUE: sum of event values per user.', max_length=20),
        ),
    ]
