# Generated by Django 5.2.17 on 2026-09-25 20:00

import apps.decisions.models
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('experiments', '0002_experiment_rollout_percentage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recommendation', models.CharField(choices=[('CONTINUE', 'Continue'), ('PAUSE', 'Pause'), ('ROLLBACK', 'Rollback'), ('INCREASE_ROLLOUT', 'Increase rollout'), ('DECREASE_ROLLOUT', 'Decrease rollout'), ('COMPLETE', 'Complete')], db_index=True, max_length=20)),
                ('confidence', models.FloatField()),
                ('confidence_label', models.CharField(max_length=10)),
                ('summary', models.TextField()),
                ('evidence', models.JSONField(default=list)),
                ('checks', models.JSONField(default=list)),
                ('inputs', models.JSONField(default=dict, help_text='Snapshot of the signals the decision was based on.')),
                ('applied_action', models.CharField(blank=True, default='', max_length=30)),
                ('from_percentage', models.PositiveIntegerField(blank=True, null=True)),
                ('to_percentage', models.PositiveIntegerField(blank=True, null=True)),
                ('triggered_by', models.CharField(default='manual', max_length=20)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='experiments.experiment')),
            ],
            options={
                'db_table': 'decisions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Guardrail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('metric_name', models.CharField(help_text="Telemetry metric name (e.g. error_rate, latency_ms) or 'conversion_rate'.", max_length=255)),
                ('source', models.CharField(choices=[('TELEMETRY', 'Production telemetry'), ('CONVERSION', 'Conversion metric')], default='TELEMETRY', max_length=20)),
                ('operator', models.CharField(choices=[('RELATIVE_INCREASE_GT', 'Relative increase vs control above (%)'), ('RELATIVE_DECREASE_GT', 'Relative decrease vs control above (%)'), ('ABSOLUTE_GT', 'Variant value above'), ('ABSOLUTE_LT', 'Variant value below')], max_length=30)),
                ('threshold', models.FloatField()),
                ('action', models.CharField(choices=[('PAUSE', 'Pause'), ('ROLLBACK', 'Rollback')], default='ROLLBACK', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardrails', to='experiments.experiment')),
            ],
            options={
                'db_table': 'guardrails',
            },
        ),
        migrations.CreateModel(
            name='RolloutChange',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('increase', 'Increase'), ('decrease', 'Decrease'), ('rollback', 'Rollback'), ('manual', 'Manual')], max_length=20)),
                ('from_percentage', models.PositiveIntegerField()),
                ('to_percentage', models.PositiveIntegerField()),
                ('reason', models.CharField(max_length=255)),
                ('automated', models.BooleanField(default=False)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('decision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='decisions.decision')),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rollout_changes', to='experiments.experiment')),
            ],
            options={
                'db_table': 'rollout_changes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RolloutPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stages', models.JSONField(default=apps.decisions.models.default_rollout_stages, help_text='Ascending rollout stages in basis points, e.g. [1000, 2500, 5000, 10000].')),
                ('auto_advance', models.BooleanField(default=False, help_text='Automatically move to the next stage when the decision engine recommends it.')),
                ('auto_rollback', models.BooleanField(default=True, help_text='Automatically roll back / pause when a guardrail is breached.')),
                ('rollback_percentage', models.PositiveIntegerField(default=1000, validators=[django.core.validators.MaxValueValidator(10000)])),
                ('min_health_score', models.PositiveIntegerField(default=70, validators=[django.core.validators.MaxValueValidator(100)])),
                ('min_stage_duration_minutes', models.PositiveIntegerField(default=60)),
                ('min_confidence', models.FloatField(default=0.8, help_text='Automatic actions require at least this decision confidence.', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('experiment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rollout_policy', to='experiments.experiment')),
            ],
            options={
                'db_table': 'rollout_policies',
            },
        ),
        migrations.AddIndex(
            model_name='decision',
            index=models.Index(fields=['experiment', '-created_at'], name='decisions_experim_f426f3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='guardrail',
            unique_together={('experiment', 'name')},
        ),
    ]
