{{- if .Values.serviceMonitor.enabled }}
{{- if .Values.api.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "experimentos.fullname" . }}-api
  labels:
    {{- include "experimentos.componentLabels" (dict "ctx" . "component" "api") | nindent 4 }}
    {{- with .Values.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "experimentos.selectorLabels" (dict "ctx" . "component" "api") | nindent 6 }}
  endpoints:
    - port: http
      path: /metrics
      interval: {{ .Values.serviceMonitor.interval }}
      scrapeTimeout: {{ .Values.serviceMonitor.scrapeTimeout }}
{{- end }}
{{- if .Values.eventConsumer.enabled }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "experimentos.fullname" . }}-event-consumer
  labels:
    {{- include "experimentos.componentLabels" (dict "ctx" . "component" "event-consumer") | nindent 4 }}
    {{- with .Values.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "experimentos.selectorLabels" (dict "ctx" . "component" "event-consumer") | nindent 6 }}
  endpoints:
    - port: metrics
      path: /metrics
      interval: {{ .Values.serviceMonitor.interval }}
      scrapeTimeout: {{ .Values.serviceMonitor.scrapeTimeout }}
{{- end }}
{{- end }}
