# Generated by Django 5.2.17 on 2026-09-25 19:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('experiments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.CharField(db_index=True, max_length=255)),
                ('bucket', models.PositiveIntegerField()),
                ('context', models.JSONField(default=dict, help_text='User attributes at time of assignment')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='experiments.experiment')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='experiments.variant')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='experiments.experimentversion')),
            ],
            options={
                'db_table': 'assignments',
                'indexes': [models.Index(fields=['user_id', 'experiment'], name='assignments_user_id_ac1b94_idx'), models.Index(fields=['experiment', 'assigned_at'], name='assignments_experim_33bf7e_idx')],
                'unique_together': {('user_id', 'experiment', 'version')},
            },
        ),
    ]
