# Generated by Django 5.2.17 on 2026-08-23 15:02

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('experiments', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TimelineEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('experiment_created', 'Experiment Created'), ('experiment_started', 'Experiment Started'), ('experiment_paused', 'Experiment Paused'), ('experiment_resumed', 'Experiment Resumed'), ('experiment_completed', 'Experiment Completed'), ('experiment_archived', 'Experiment Archived'), ('version_created', 'Version Created'), ('rollout_changed', 'Rollout Changed'), ('health_score_changed', 'Health Score Changed'), ('srm_detected', 'SRM Detected'), ('guardrail_breached', 'Guardrail Breached'), ('interaction_detected', 'Interaction Detected'), ('paradox_detected', "Simpson's Paradox Detected")], db_index=True, max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('detail', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_events', to='experiments.experiment')),
            ],
            options={
                'db_table': 'timeline_events',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['experiment', '-created_at'], name='timeline_ev_experim_69ede2_idx')],
            },
        ),
    ]
