# Generated by Django 5.2.17 on 2026-09-25 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timelineevent',
            name='event_type',
            field=models.CharField(choices=[('experiment_created', 'Experiment Created'), ('experiment_started', 'Experiment Started'), ('experiment_paused', 'Experiment Paused'), ('experiment_resumed', 'Experiment Resumed'), ('experiment_completed', 'Experiment Completed'), ('experiment_archived', 'Experiment Archived'), ('version_created', 'Version Created'), ('rollout_changed', 'Rollout Changed'), ('health_score_changed', 'Health Score Changed'), ('srm_detected', 'SRM Detected'), ('guardrail_breached', 'Guardrail Breached'), ('interaction_detected', 'Interaction Detected'), ('paradox_detected', "Simpson's Paradox Detected"), ('anomaly_detected', 'Anomaly Detected'), ('decision_made', 'Decision Made'), ('rollback_triggered', 'Rollback Triggered')], db_index=True, max_length=50),
        ),
    ]
