# Generated by Django 5.2.17 on 2026-09-25 20:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
        ('experiments', '0002_experiment_rollout_percentage'),
        ('organizations', '0002_membership'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Set for every entry; the only scope for organization-level events.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='organizations.organization'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('EXPERIMENT_CREATED', 'Experiment created'), ('EXPERIMENT_STARTED', 'Experiment started'), ('EXPERIMENT_PAUSED', 'Experiment paused'), ('EXPERIMENT_RESUMED', 'Experiment resumed'), ('EXPERIMENT_COMPLETED', 'Experiment completed'), ('EXPERIMENT_ARCHIVED', 'Experiment archived'), ('STATUS_CHANGED', 'Status changed'), ('VERSION_CREATED', 'Version created'), ('ROLLOUT_CHANGED', 'Rollout changed'), ('ROLLBACK_TRIGGERED', 'Rollback triggered'), ('CONFIG_CHANGED', 'Configuration changed'), ('PERMISSION_CHANGED', 'Permission changed'), ('API_KEY_CREATED', 'API key created')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='experiment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='experiments.experiment'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['organization', '-created_at'], name='audit_logs_organiz_86ff70_idx'),
        ),
    ]
