# Generated by Django 5.2.17 on 2026-09-25 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0003_backfill_organization_and_actions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('EXPERIMENT_CREATED', 'Experiment created'), ('EXPERIMENT_STARTED', 'Experiment started'), ('EXPERIMENT_PAUSED', 'Experiment paused'), ('EXPERIMENT_RESUMED', 'Experiment resumed'), ('EXPERIMENT_COMPLETED', 'Experiment completed'), ('EXPERIMENT_ARCHIVED', 'Experiment archived'), ('STATUS_CHANGED', 'Status changed'), ('VERSION_CREATED', 'Version created'), ('ROLLOUT_CHANGED', 'Rollout changed'), ('ROLLBACK_TRIGGERED', 'Rollback triggered'), ('CONFIG_CHANGED', 'Configuration changed'), ('PERMISSION_CHANGED', 'Permission changed'), ('API_KEY_CREATED', 'API key created'), ('API_KEY_REVOKED', 'API key revoked')], db_index=True, max_length=50),
        ),
    ]
